### ISSUE TITLE
Duplicate extension name at EOG

### ISSUE THREAD

**Issue by tukusejssirs** [BjoernDaase/noannoyance#4]
I love this extension. I have just noticed that this extension is (kind of) fork of [one made by sindex](https://github.com/sindex/no-annoyance), but it shares the same name at EOG and thus there are two extensions of the same name.

I think that one of them needs to be renamed:
- @sindex’ one to include something like `OLD` or `UNMAINTAINED`;
- yours to include something like `v2` or whatever you wish.

**Comment by BjoernDaase** [comment]
Thanks for your input @tukusejssirs!
I agree with the point you point you make, disambiguating the names seems like a good idea. Unfortunately, unmaintained extensions do not get removed from EOG and I also do not have access on the other extensions, so we have to somehow rename this one. If no one comes up with a good idea in the near future, I will just rename it to `NoAnnoyance v2`.

**Comment by tukusejssirs** [comment]
Good to know you agree with me! :smiley:

`v2` is nice when we talk about the name, but do you what to change the repo name / ext UUID too? Then `noannohance_v2` might not be that good.

**Comment by BjoernDaase** [comment]
The UUIDs are already different. See https://github.com/BjoernDaase/noannoyance/blob/b9889b14a74b9a4d9ece141e858abd042040ca87/metadata.json#L10 vs. https://github.com/sindex/no-annoyance/blob/f21d09a12701fce1a3179ea6b8c7c10efc731275/metadata.json#L12. 
The same applies for the repository names, which are unique due to their name space.

**Comment by tukusejssirs** [comment]
You’re right, it’s not necessary. :)
